In [ ]:
tflearn真好用   ，使用简单！！！

In [26]:
import numpy as np
import pandas as pd
df = pd.read_csv('customer_churn.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [2]:
#生成特征矩阵
X = df.loc[:,['CreditScore', 'Geography', 'Gender' , 'Age', 'Tenure', 'Balance','NumOfProducts', 
              'HasCrCard', 'IsActiveMember', 'EstimatedSalary']]
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [3]:
y = df.Exited
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [4]:
#LabelEncoder将类别信息变成数值，国家和地区
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder1  = LabelEncoder()
X.Geography = labelencoder1.fit_transform(X.Geography)
labelencoder2 = LabelEncoder()
X.Gender = labelencoder2.fit_transform(X.Gender)
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [5]:
df.Geography.unique()#这里国家的数字化并不合适，因为012之间是有数值影响的，现在使用OneHotEncoder解决

array(['France', 'Spain', 'Germany'], dtype=object)

In [6]:
onehotencoder = OneHotEncoder(categorical_features = [1] )
X = onehotencoder.fit_transform(X).toarray()

In [7]:
X[0]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       0.0000000e+00, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [8]:
#删除第一列，避免“虚拟变量陷阱”。。。。。这里还没搞懂原理
X = np.delete(X, [0] , 1)
X[0]

array([0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [9]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [10]:
#转列向量
y = y[:,np.newaxis]
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [11]:
#使用onehotencoder自动的根据标签数量转化为向量形式标签
onehotencoder = OneHotEncoder()
y = onehotencoder.fit_transform(y).toarray()
y

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [12]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size  = 0.2, random_state = 0)
#保证在不同的平台上划分都一样
len(X_train)


8000

In [13]:
len(X_test)

2000

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [15]:
from sklearn import tree#引入决策树 拟合训练数据
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [16]:
y_pred = clf.predict(X_test)
y_pred
y_pred.shape

(2000, 2)

In [17]:
#下面生成分析报告
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.89      0.87      0.88      1595
          1       0.51      0.56      0.54       405

avg / total       0.81      0.80      0.81      2000



In [18]:
#深度学习进行结果的优化
import tflearn

/Users/kelang-tian/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [19]:
#神经网络的建立  搭积木？？？
#神经元数量：把输入层的神经元数量，加上输出层神经元数量，除以2取整
#大家都这么做，貌似是哲学调参？
net = tflearn.input_data(shape=[None, 11])
net = tflearn.fully_connected(net, 6, activation = 'relu')
net = tflearn.fully_connected(net, 6, activation = 'relu')
net = tflearn.fully_connected(net, 6, activation = 'relu')
#输出层的建立
net = tflearn.fully_connected(net, 2, activation = 'softmax')
net = tflearn.regression(net)
#生成模型
model = tflearn.DNN(net)
model.fit(X_train, y_train, n_epoch=30, batch_size=32, show_metric=True)


#n_epoch：数据训练几个轮次。
#batch_size：每一次输入给模型的数据行数。
#show_metric：训练过程中要不要打印结果。


Training Step: 7499  | total loss: 0.37470 | time: 0.582s
| Adam | epoch: 030 | loss: 0.37470 - acc: 0.8510 -- iter: 7968/8000
Training Step: 7500  | total loss: 0.36570 | time: 0.584s
| Adam | epoch: 030 | loss: 0.36570 - acc: 0.8534 -- iter: 8000/8000
--


In [21]:
X_test[0]

array([ 1.75486502, -0.57369368, -0.55204276, -1.09168714, -0.36890377,
        1.04473698,  0.8793029 , -0.92159124,  0.64259497,  0.9687384 ,
        1.61085707])

In [22]:
y_pred = model.predict(X_test)
y_pred[0]

array([0.7098911 , 0.29010892], dtype=float32)

In [23]:
y_test[0]

array([1., 0.])

In [25]:
acc = model.evaluate(X_test, y_test)
print('Test acc: %0.4f%%' %(acc[0]*100))

Test acc: 86.5000%
